default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling

development:
  <<: *default
  database: vaccine_locator_app_development
  host: localhost

test:
  <<: *default
  database: vaccine_locator_app_test
  host: localhost

production:
  <<: *default
  database: vaccine_locator_app_production
  username: vaccine_locator_app
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_CONNECTION_POOL_URL'] || ENV['DATABASE_URL'] %>
  prepared_statements: false
  advisory_locks: false
  checkout_timeout: <%= ENV['DATABASE_CHECKOUT_TIMEOUT'] || 5 %>
  reaping_frequency: <%= ENV['DATABASE_REAPING_FREQUENCY'] || nil %>
  statement_timeout: <%= ENV['DATABASE_STATEMENT_TIMEOUT'] || 5000 %>
